### ISSUE TITLE
[Site Request] TamilDhool

### ISSUE THREAD

**Issue by bachig26** [daarkdemon/cs-darkdemon-extensions#1]
TamilDhool Domain: https://www.tamildhool.net

TamilDhool is a streaming site for Tamil Serials & Shows from Sun TV, Zee Tamil, Vijay TV, Kalaignar TV and Colors Tamil.

**Comment by daarkdemon** [comment]
Added in [LikDev Repo](https://github.com/LikDev-256/likdev256-tamil-providers) LikDev-256/likdev256-tamil-providers@d0872af9c7ba0dda7731707e2b13dbc53b71dfd2
