### ISSUE TITLE
[Site Request] techmaxlive

### ISSUE THREAD

**Issue by OshekharO** [daarkdemon/cs-darkdemon-extensions#21]
Link: http://techmaxlive.ml

Hii can you please try this one? It have almost everything Jiotv,Voot,MX Player,Zee5 and many more.

https://zeeliv.tk
http://extratvteam.gq

Check this out too

**Comment by daarkdemon** [comment]
Added techmaxlive and zeeliv

**Comment by ajimal173** [comment]
dear sir,

its my request u to add site for hindi serial pls add if possible any one of from given below sites

**https://yodesiserial.su/
https://www.bollyzone.tv/**

thank u,
**AJIMAL KHAN**

**Comment by ajimal173** [comment]
> dear sir,
> 
> its my request u to add site for hindi serial pls add if possible any one of from given below sites
> 
> **https://yodesiserial.su/ https://www.bollyzone.tv/**
> 
> thank u, **AJIMAL KHAN**

hi bro,

this below link better than above links pls add if u wish even u can remove above also just my request.
https://wserials.com
