### ISSUE TITLE
Getting Error while playing anything from Ibomma Provider on Cloudstream App

### ISSUE THREAD

**Issue by deepu458** [daarkdemon/cs-darkdemon-extensions#27]
Hi Developer, When I try to play any movie from IBomma, it throws the below error message. This is happening in CloudStream app in Android 13

Error Message: No Links Found Remote Error Error_Code_IO_Network_Connection_Failed(2001) Source error

![Screenshot_20221216_192252_CloudStream](https://user-images.githubusercontent.com/42040361/208212792-c5fe150c-4836-4726-90fa-fe92f791d60c.jpg)

**Comment by daarkdemon** [comment]
fixed in 931ab31fea3b2b97b711c8a1e900bda098ec690f
